export const tags = [
  {
    parent: 'Music & Concerts',
    children: [
      '🎤 Concerts',
      '🎪 Festivals',
      '🎸 Live Bands',
      '🎧 DJ Sets',
      '🎤 Karaoke',
      '🎭 Musicals & Operas',
      '🎤 Singing',
      '🎹 Playing an Instrument',
      '🎛️ Music Production',
      '💿 Vinyl Collecting',
      '🎶 Pop',
      '🤘 Rock',
      '🎤 Hip Hop',
      '🎵 R&B',
      '🤠 Country',
      '🎛️ Electronic',
      '🎷 Jazz',
      '🎻 Classical',
      '🎵 Acoustic',
      '🎸 Indie',
    ],
  },
  {
    parent: 'Nightlife & Parties',
    children: [
      '🎪 Clubs',
      '🎉 Parties',
      '🌈 Raves',
      '🎧 DJ Sets',
      '🏠 House Parties',
      '💃 Dance Parties',
      '🎵 Music Events',
    ],
  },
  {
    parent: 'Bars & Lounges',
    children: [
      '🍻 Bars',
      '🍹 Lounges',
      '🕔 Happy Hours',
      '🏙️ Rooftop Bars',
      '🍺 Pub Crawls',
      '🔍 Speakeasies',
      '🍷 Wine Bars',
      '🍸 Cocktail Nights',
      '🍻 Pubs',
    ],
  },
  {
    parent: 'Festivals & Fairs',
    children: [
      '🎵 Music Festivals',
      '🎨 Arts Festivals',
      '🎬 Film Festivals',
      '🌍 Cultural Festivals',
      '🍔 Food Festivals',
      '🍺 Beer Festivals',
      '🍷 Wine Festivals',
      '🏪 Street Fairs',
      '🧶 Craft Fairs',
      '📚 Book Fairs',
      '🏢 Trade Shows',
      '🏫 School Fairs',
      '🎡 Carnivals',
      '🎠 County Fairs',
    ],
  },
  {
    parent: 'Markets & Pop-ups',
    children: [
      '🌽 Farmers Markets',
      '✨ Pop-up Markets',
      '🏪 Street Markets',
      '🧺 Flea Markets',
      '🍜 Street Food Markets',
      '👕 Vintage Markets',
      '✋ Handmade Markets',
      '🎨 Artisan Pop-ups',
    ],
  },
  {
    parent: 'Sports Events',
    children: [
      '🏟️ Stadium Games',
      '📺 Watch Parties',
      '🏀 Street Sports',
      '💪 Fitness Classes',
      '🎮 Esports Tournaments',
      '🧘 Yoga Sessions',
      '🏃 Running Clubs',
      '🥾 Hiking Groups',
      '🏀 Basketball Games',
      '⚽ Soccer Matches',
      '🏋️ Gym Workouts',
      '🏁 Marathons',
      '🚴 Cycling',
    ],
  },
  {
    parent: 'Art & Culture',
    children: [
      '🏛️ Museums',
      '🖼️ Art Exhibitions',
      '🎨 Gallery Openings',
      '📖 Book Readings',
      '✒️ Poetry Slams',
      '🏛️ Historical Tours',
      '🎬 Film Screenings',
      '🏺 Pottery Classes',
      '🎨 Painting Workshops',
      '🎨 Street Art',
      '🗿 Sculpture Gardens',
      '🎓 Workshops',
      '🎤 Lectures & Talks',
      '🏛️ Architecture Tours',
    ],
  },
  {
    parent: 'Show & Performances',
    children: [
      '🎭 Theater',
      '😂 Comedy Shows',
      '💃 Dance Performances',
      '🎭 Musicals & Operas',
      '🎤 Improv Comedy',
      '🎩 Magic Shows',
      '🎵 Concerts',
      '🎸 Live Bands',
      '🤸 Acrobatics',
      '🎪 Puppet Shows',
      '🎤 Open Mic Nights',
    ],
  },
  {
    parent: 'Community & Social',
    children: [
      '👥 Meetups',
      '❤️ Charity Events',
      '🏫 School Events',
      '🙏 Religious Gatherings',
      '🏘️ Local Clubs',
      '🤲 Volunteering',
      '🎲 Game Nights',
      '🎨 Hobby Groups',
      '🤝 Networking Events',
      '💙 Support Groups',
      '🔧 Community Workshops',
    ],
  },
  {
    parent: 'Food & Drink events',
    children: [
      '🍷 Wine Tastings',
      '🚚 Food Trucks',
      '🍻 Brewery Tours',
      '🍸 Cocktail Nights',
      '☕ Coffee Popups',
      '👩‍🍳 Cooking Classes',
      '🍽️ Restaurant Openings',
      '🍳 Brunch',
      '🌮 Taco Tuesdays',
      '🍻 Happy Hour Specials',
    ],
  },
  {
    parent: 'Family & Kids',
    children: [
      '🎪 Carnivals',
      '🎪 Puppet Shows',
      '🎵 Kids Concerts',
      '🐯 Zoo Events',
      '📚 Story Time',
      '🌳 Park Playdates',
      '📚 Library Events',
      '🏫 School Fairs',
      '🎩 Magic Shows',
      '⛳ Mini Golf',
      '🐠 Aquarium Visits',
      '🤸 Trampoline Parks',
    ],
  },
  {
    parent: 'Special & Seasonal',
    children: [
      '🎉 Holidays',
      '🎊 Parades',
      '🎆 Fireworks',
      '🎓 Graduations',
      '🎄 Seasonal Pop-ups',
      '🎉 New Year\'s Eve',
      '🎃 Halloween',
      '🎄 Christmas',
      '💝 Valentine\'s Day',
      '🌈 Pride',
      '🦃 Thanksgiving',
      '🐣 Easter',
      '🕎 Hanukkah',
      '🪔 Diwali',
      '🌙 Ramadan',
      '🏮 Chinese New Year',
    ],
  },
];
// "filters": {
//   "time_of_day": ["Morning", "Afternoon", "Evening", "Late Night"],
//   "vibe": ["Chill", "Energetic", "Romantic", "Family-Friendly", "Exclusive"],
//   "size": ["Small", "Medium", "Large", "Massive"]
// }
